#̷\  ===================================================================
#̷\  PowerShell Module -- PowerShell.Module.ClientTools
#̷\  
#̷\  Manifest File Generated on Mon, 04 Aug 2025 05:55:36 GMT
#̷\  Current Git Revision ae37ccf97e9ccbc358b4bd0ec2f041973209786a
#̷\  ===================================================================


@{


    RootModule        =  'PowerShell.Module.ClientTools.psm1'

    ModuleVersion     = '1.7.59
'

    GUID              = 'bfdffbe7-4609-4f14-a14f-3aeda8f73f5f'

    CompanyName       = 'Unknown'

    Author            = 'Guillaume Plante'

    Copyright         = '(c) 2020 Guillaume Plante. All rights reserved.'

    Description       = 'MODULE PowerShell.Module.ClientTools on 7:43 PM'

    PowerShellVersion = '5.0'

    RequiredAssemblies = @()

    # Private data to pass to the module specified in RootModule. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('PowerShell.Module.ClientTools')
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/arsscriptum/PowerShell.Module.ClientTools/blob/main/COPYING'
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/arsscriptum/PowerShell.Module.ClientTools'
        } # End of PSData hashtable
    } # End of PrivateData hashtable


    #̷\  ===================================================
    #̷\     ＭＯＤＵＬＥ ＥＸＰＯＲＴＥＤ ＦＵＮＣＴＩＯＮＳ
    #̷\  ===================================================

	# !NOTE! --- The following functions declaration was automatically generated by the build script. ---
	FunctionsToExport = @(

		# --- Exported Functions from BlockWebsite.ps1 ---
		"Block-BraveWebsite",

		# --- Exported Functions from BlueScreen.ps1 ---
		"Show-BlueScreen",

		# --- Exported Functions from CheckAndGet.ps1 ---
		"Invoke-ValidateScriptsVersion",
		"Update-LocalVersionValue",
		"Get-LatestVersionString",
		"Get-LatestScriptsVersion",
		"Get-OnlineVersionIWebR",
		"Update-LocalVersionValue",
		"Get-OnlineVersionCurl",
		"Get-OnlineVersionIRestM",
		"Test-LatestVersion",
		"Get-LocalCurrentVersionString",
		"Invoke-GetVersionString",
		"Get-OnlineVersionWGet",

		# --- Exported Functions from Config.ps1 ---
		"Set-ClientToolsServer",
		"Get-ClientToolsModuleInformation",
		"Get-ClientToolsModuleRegistryPath",
		"Test-ClientToolsModuleConfig",
		"Get-ClientToolsServer",
		"Get-ClientToolsDefaultUsername",
		"Get-ClientToolsDevAccountOverride",
		"Get-ClientToolsModuleUserAgent",
		"Set-ClientToolsDevAccountOverride",
		"Get-ClientToolsAppCredentialID",
		"Get-ClientToolsUserCredentialID",
		"Set-ClientToolsDefaultUsername",

		# --- Exported Functions from ConfigureWellKnownPaths.ps1 ---
		"Update-WellKnownPaths",
		"Set-EnvironmentVariable",
		"Publish-RegistryChanges",
		"Publish-SettingsUpdated",
		"Update-ModulesShortcuts",
		"Get-DocumentsPath",
		"Get-CustomPathValues",

		# --- Exported Functions from ConfigureWindowsTerminal.ps1 ---
		"Edit-TerminalConfig",
		"Save-TerminalConfig",
		"Get-WindowsTerminalConfigPath",
		"Get-WindowsTerminalProfilePath",

		# --- Exported Functions from ControlMouse.ps1 ---
		"Get-RegistryInstanceId",
		"Set-RegistryInstanceId",
		"Get-PSControlsRegistryRoot",
		"Disable-LocalMouse",
		"Get-LocalMouseStatus",
		"Enable-LocalMouse",

		# --- Exported Functions from ConvertScriptVar.ps1 ---
		"ConvertTo-ScriptVariable",

		# --- Exported Functions from Credential.ps1 ---
		"Get-ElevatedCredential",
		"Get-AppCredentials",
		"Register-AppCredentials",
		"Remove-AppCredentials",
		"Show-RegisteredCredentials",
		"Get-CredentialsRegistryPath",
		"Get-CoreModuleRegistryPath",

		# --- Exported Functions from CustomPathFunctions.ps1 ---
		"Push-CodeTemplates",
		"Push-WinSandbox",
		"Push-Templates",
		"Push-CodeSandbox",
		"Push-ScriptsSandbox",
		"Push-PowerShellSandbox",
		"Push-Sandbox",
		"Push-ProfilePath",
		"Push-MyCode",
		"Push-DevelopmentRoot",
		"Push-RedditSupport",
		"Push-siteroot",
		"Push-wwwroot2",
		"Push-wwwroot",
		"Push-ToolsRoot",
		"Push-ScriptsRoot",
		"Push-DejaToolsRootDirectory",
		"Push-MyDocuments",
		"Push-moddev",

		# --- Exported Functions from Decode.ps1 ---
		"Invoke-DecodeFiles",
		"Start-DecodeFiles",
		"Export-DataFiles",
		"Invoke-CombineSplitFiles",
		"Get-ScriptEncodeAppCredentials",
		"Invoke-AutoUpdateProgress",
		"Merge-DataFile",

		# --- Exported Functions from Encode.ps1 ---
		"Invoke-EncodeAllNewScripts",
		"Get-ScriptEncodeAppCredentials",
		"Update-VersionNumber",
		"Invoke-AutoUpdateProgress",
		"Invoke-SplitDataFile",
		"Split-DataFile",
		"Import-DataFiles",
		"Invoke-EncodeFiles",
		"Start-EncodeFiles",

		# --- Exported Functions from Exception.ps1 ---
		"Show-ExceptionDetails",
		"Test-ExceptionDetailsTextBox",
		"Get-ExceptionDetailsTextBox",
		"Enable-ExceptionDetailsTextBox",
		"New-ErrorRecord",
		"Disable-ExceptionDetailsTextBox",

		# --- Exported Functions from ExportConnectionsData.ps1 ---
		"Get-HomePath",
		"Get-LogsPath",
		"Export-NetConnections",

		# --- Exported Functions from ExportSystemInfo.ps1 ---
		"Export-SystemInfo",

		# --- Exported Functions from GetConns.ps1 ---
		"Get-V6ConnectionsOnly",
		"Get-ActiveConnectionsListening",
		"Get-ConnectionDoc",
		"Get-ActiveConnectionsWithLocalPort",
		"Get-ActiveConnectionsEstablished",
		"Get-ActiveConnectionsNetstat",
		"Get-ActiveConnectionsOnly",
		"Test-ExternalPort",
		"Get-ExternalPortStateReport",
		"Get-ExternalPortState",
		"Invoke-TcpConView",
		"Get-LocalOpenPorts",
		"Invoke-FilterRemoteAddresses",
		"Get-NetStatExe",

		# --- Exported Functions from GetCurrentContext.ps1 ---
		"Get-CurrentContext",

		# --- Exported Functions from GetEnvPath.ps1 ---
		"Get-EnvPath",

		# --- Exported Functions from GetFnSource.ps1 ---
		"Get-FunctionSource",

		# --- Exported Functions from GetHistory.ps1 ---
		"Get-HomePath",
		"Clear-PsHistory",
		"Show-PsHistory",

		# --- Exported Functions from GetLoggedInUsers.ps1 ---
		"Get-LoggedInUsers",

		# --- Exported Functions from GetTerminalStartingDirectory.ps1 ---
		"Get-TerminalStartingDirectory",

		# --- Exported Functions from Helpers.ps1 ---
		"Get-DateString",
		"Get-UnixTime",
		"ConvertTo-UnixTime",
		"Get-DateForFileName",
		"ConvertFrom-UnixTime",
		"Write-ClientToolsHost",
		"ConvertFrom-Ctime",
		"Write-ProgressHelper",
		"Show-ModuleInstallPaths",
		"Wait-ClientToolsModuleUpdate",
		"ConvertTo-CTime",

		# --- Exported Functions from History.ps1 ---
		"Out-SplitMatchLine",
		"Search-StringInFile",
		"Get-FileInfoWithTimeSpan",
		"Search-PsHistory",

		# --- Exported Functions from Initialize.ps1 ---
		"Uninitialize-ClientToolsModule",
		"Initialize-ClientToolsModule",
		"AutoInitialize-ClientToolsModule",

		# --- Exported Functions from MessageBox.ps1 ---
		"Show-MessageBoxVideoUrl",
		"Show-MessageBoxInfo",
		"Show-MessageBoxRestart",
		"Show-MessageBoxVideoSydney",
		"Show-BeAdvisedSydney",
		"Show-MessageBoxScriptError",
		"Show-MessageBoxServices",
		"Show-MessageBoxAsyncPing",
		"Show-MessageBoxVideoUrlExtended",
		"Show-MessageBoxError",
		"Show-MessageBoxStandby",
		"Show-MessageBoxException",
		"Register-ScriptAssemblies",
		"Show-UserInfo",
		"Get-MessageBoxResult",
		"Show-Popup",
		"Show-SimpleMessageBox",
		"Show-MessageBoxVoice",
		"Test-SimpleMsgBox2",
		"Test-SimpleMsgBox",
		"Show-MessageBox",
		"Test-Popupcolors",

		# --- Exported Functions from ModulesPathFunctions.ps1 ---
		"Push-Modter2K",
		"Push-ModWorkflowTools",
		"Push-ModWindowsHost",
		"Push-ModTorrentsManager",
		"Push-ModTools",
		"Push-ModTerminal",
		"Push-ModTakeOwnership",
		"Push-ModShim",
		"Push-ModShellGPT",
		"Push-ModReddit",
		"Push-ModProfileUtils",
		"Push-ModOpenAI",
		"Push-ModMiniPc",
		"Push-ModManageMini",
		"Push-ModGithub",
		"Push-ModExpressVPN",
		"Push-ModDownloader",
		"Push-ModDocker",
		"Push-ModCryptography",
		"Push-ModCore",
		"Push-ModCompiler",
		"Push-ModAssert",
		"Push-Mod1190",
		"Push-Mod1138",
		"Push-ModNtRights",

		# --- Exported Functions from ModuleUpdater.ps1 ---
		"Invoke-ClientToolsAutoUpdate",
		"Get-ClientToolsAutoUpdateOverride",
		"New-ClientToolsModuleVersionFile",
		"Set-ClientToolsAutoUpdateOverride",
		"Get-ClientToolsModuleVersionPath",

		# --- Exported Functions from ModuleVersion.ps1 ---
		"Get-ClientToolsModuleVersion",

		# --- Exported Functions from NamedPipe.ps1 ---
		"New-NamedPipeServer",
		"New-NamedPipeServerAsync",
		"Start-NamedPipeServerJob",
		"New-NamedPipeClient",
		"Send-NamedPipeData",

		# --- Exported Functions from NetDelayedTask.ps1 ---
		"New-EncodedScheduledTask",
		"Open-QueuedCommandLogs",
		"Stop-QueuedCommandProcessor",
		"Start-QueuedCommandProcessor",
		"Invoke-ProcessQueuedCommands",
		"New-DelayedScheduledTask",

		# --- Exported Functions from OpenPage.ps1 ---
		"Invoke-OpenPageSecurityAdvisory",
		"Stop-OpenPageTask",
		"Invoke-OpenPageDesjardins",
		"Stop-PowerShellProcesses",
		"Open-CustomPage",
		"Stop-PidFromTempFile",
		"Read-OpenCustomPageLogFile",
		"Save-CurrentPidToTempFile",
		"New-OpenPageTask",

		# --- Exported Functions from PowerTools.ps1 ---
		"Disable-AllPowerValues",
		"Disable-InactivityLock",
		"Disable-LockScreenTimeout",
		"Disable-Hibernate",
		"Set-PowerTimeouts",
		"Get-PowerTimeouts",
		"Get-PowerCfgLanguage",
		"Disable-SleepAndDisplayOff",

		# --- Exported Functions from ProcessData.ps1 ---
		"Invoke-EncodeAllNewScripts",
		"Update-VersionNumber",
		"Start-DecodeFiles",
		"Start-EncodeFiles",
		"Invoke-EncodeFiles",
		"Invoke-DecodeFiles",
		"Export-DataFiles",
		"Merge-DataFile",
		"Invoke-CombineSplitFiles",
		"Split-DataFile",
		"Invoke-SplitDataFile",
		"Invoke-AutoUpdateProgress",
		"Import-DataFiles",

		# --- Exported Functions from processlist.ps1 ---
		"Get-ProcessList",

		# --- Exported Functions from Prompt.ps1 ---
		"Reset-Prompt",
		"Set-SmallPrompt",
		"Show-Prompt",
		"Show-Header",
		"Invoke-IsAdministrator",
		"Show-SystemInfo",
		"Start-Explorer",
		"Show-PromptNoPath",
		"Invoke-IsAdministrator",

		# --- Exported Functions from QueuedCommands.ps1 ---
		"Process-QueuedCommands",
		"Clear-QueuedCommands",
		"New-QueuedCommand",

		# --- Exported Functions from Record.ps1 ---
		"Invoke-MapRemoteDrive",
		"Invoke-StartRecord",
		"Invoke-MapRemoteDrive",
		"Add-TaskLog",
		"Save-Screenshot",
		"Start-SaveScreenshots",
		"Read-RecordLogFile",
		"Invoke-StopRecord",

		# --- Exported Functions from Registry.ps1 ---
		"Set-RegistryValue2",
		"Get-UserConfirmationRegDel",
		"Delete-RegistryKeyTree",
		"New-RegistryValue",
		"Find-EntriesMatchingName",
		"Publish-SettingsUpdated",
		"Get-RegistryValue",
		"Get-RegistryValue",
		"Test-RegistryValue",
		"Remove-RegistryValue",
		"Set-RegistryValue",

		# --- Exported Functions from RemoteDesktop.ps1 ---
		"Enable-RemoteDesktop",

		# --- Exported Functions from RestartScript.ps1 ---
		"Invoke-RestartWithMessage",

		# --- Exported Functions from SaveEditProfile.ps1 ---
		"Get-GitExecutablePath",
		"Save-Profile",
		"Edit-Profile",
		"Reload-Profile",
		"Sync-Profile",

		# --- Exported Functions from SearchPattern.ps1 ---
		"Search-Pattern",

		# --- Exported Functions from SelectUser.ps1 ---
		"Select-LoggedInUser",

		# --- Exported Functions from SetFirewallConfig.ps1 ---
		"isIE",
		"alertLoc",
		"Set-FirewallConfiguration",

		# --- Exported Functions from SetMappedDrives.ps1 ---
		"Test-AreNetworkDrivesMapped",
		"Register-NetworkDrive",
		"Unregister-NetworkDrive",
		"Test-TemporaryDriveExist",
		"Register-NetworkDrivesMapping",
		"Unregister-NetworkDrivesMapping",
		"Invoke-RemapDrives",

		# --- Exported Functions from ShowSydneyMsgBox.ps1 ---
		"Show-Sydney",
		"ConvertFrom-Base64CompressedScriptBlock",
		"Show-MessageBoxVideoSydney",

		# --- Exported Functions from Subl.ps1 ---
		"Invoke-SublimeText",

		# --- Exported Functions from TestPorts.ps1 ---
		"Test-Port",

		# --- Exported Functions from Touch.ps1 ---
		"Invoke-TouchFile",

		# --- Exported Functions from UnlockScripts.ps1 ---
		"Update-UnlockScripts",

		# --- Exported Functions from UpdateLoginScripts.ps1 ---
		"New-QueuedCommand",
		"Process-QueuedCommands",
		"Clear-QueuedCommands",

		# --- Exported Functions from WgetDl.ps1 ---
		"Invoke-WGetDownloadFile",
		"Invoke-Aria2DownloadFile",
		"Test-Aria2DownloadFile",
		"Test-WGetDownloadFile",

		# --- Exported Functions from WinUpdateNotify.ps1 ---
		"Get-XamlUiContent",
		"Invoke-WinUpdateTask",
		"Show-WinUpdateNotification",
		"Invoke-WinUpdateTask",

		# --- Exported Functions from WriteUtils.ps1 ---
		"Write-ConsoleExtended",
		"Show-Countdown")
	

    #̷\  ===================================================
    #̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＥＸＰＯＲＴＥＤ ＡＬＩＡＳＥＳ
    #̷\  ===================================================

	# !NOTE! --- The following alias declaration was automatically generated by the build script. ---
	# List of all aliases packaged with this module

	AliasesToExport = @(
		"aria2dl",
		"clearhistory",
		"conactive",
		"conestablished",
		"conlistening",
		"conndoc",
		"connsexport",
		"constat",
		"conview",
		"conviewports",
		"DoScriptsCheck",
		"gethomepath",
		"grep",
		"isadmin",
		"showhistory",
		"subl",
		"sysrestart",
		"touch",
		"viewconnections",
		"wgetdl",
		"x")

    #̷\  ===================================================
    #̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＦＩＬＥＳ 
    #̷\ （ＩＦ ＣＯＭＰＲＥＳＳＥＤ， ＷＩＬＬ ＢＥ ＥＭＰＴＹ）
    #̷\  ===================================================

	FileList = @()

}




